extends: airbnb-base
plugins:
  - import
rules:
  brace-style: [2, "stroustrup"]
  comma-dangle:
    - error
    -
      arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
